### ISSUE TITLE
FAlta a possibilidade da pessoa ouvir sem se cadastrar.

### ISSUE THREAD

**Issue by AlbertoAlfredo** [CloudRadioProject/BugReport#89]
Nem todos querem se cadastrar para ouvir um episodio ou outro de podcast e esse sistema está travando quem só quer ouvir

**Comment by lczanatta** [comment]
Alberto, quando o sistema for lançado como um todo. A possibilidade de
ouvir sem logar vai existir. Mas não vai ser a melhor experiência para o
ouvinte. Pois não poderemos indicar novos podcasts segundo o gostos do
usuário.

Em 8 de jan de 2017 16:48, "Alberto Alfredo" <notifications@github.com>
escreveu:

Nem todos querem se cadastrar para ouvir um episodio ou outro de podcast e
esse sistema está travando quem só quer ouvir

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/CloudRadioProject/BugReport/issues/89>, or mute the
thread

**Comment by AlbertoAlfredo** [comment]
Infelizmente o problema não fica na melhor experiência e sim em ter uma experiência pq os meus amigos que não tem o cadastro e querem me ouvir e que estão dispostos a se cadastrar não conseguem, aparece a mensagem que infelizmente não podem liberar acesso a todos os usários e em breve libera o cadastro.
Então o sistema como está em Alpha teria de ter isso para não restringir a possibilidade de ouvintes, por agora terei que encontrar outra plataforma para postar os episódios que estou fazendo.
O Cloudradio como está só funciona pra quem tem um feed por fora e está mantendo a plataforma como backup até a liberação total dela

**Comment by GabrielRamoz** [comment]
Estou tendo o mesmo tipo de problema, enviando o podcast que publiquei aqui e ninguém conseguindo acessar. Quando seria liberada a utilização por pessoas que não estivessem logadas?

**Comment by AlbertoAlfredo** [comment]
Eu deixei de lado a plataforma por enquanto por esse problema, em vez de
ajudar se tornou um funil estreito me atrapalhando, a ideia é linda mas só
falta ficar pronta

Em ter, 17 de jan de 2017 22:06, GabrielRamoz <notifications@github.com>
escreveu:

**Comment by lczanatta** [comment]
@Caothic  e @GabrielRamoz .
Agora o site ta possibilitando os usuários a acessar o site e ouvir os podcasts sem precisar logar/cadastrar.
Mas seria legal vocês incentivar os seus ouvintes a se cadastrarem. Pois assim, as estatísticas vão ser mais precisas. Com isso futuramente as propagandas serão melhores direcionadas para seu publico.  
Obrigado pelo seu feedback e desculpa a demorada de liberar o site para não logados.
